on:
  push:
    branches:
      - "main"
jobs:
  run_unit_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '>=1.19.0'
      - run: make test
  run_integration_tests:
    runs-on: ubuntu-latest
    env:
      # each integration test in pipeline should be done within the 4 minutes
      SAKERHET_INTEGRATION_TEST_TIMEOUT: 240
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '>=1.19.0'
      - run: make integration-test
